### ISSUE TITLE
Getting OOM error at the middle of the training in asr_swbd recipe on lstm encoder decoder model

### ISSUE THREAD

**Issue by asifjalal** [freewym/espresso#60]
### error message
```
2021-03-19 12:09:30 | WARNING | fairseq.trainer | attempting to recover from OOM in forward/backward pass
2021-03-19 12:09:30 | WARNING | fairseq.trainer | OOM: Ran out of memory with exception: CUDA out of memory. Tried to allocate 600.00 MiB (GPU 0; 10.92 GiB total capacity; 8.55 GiB already allocated; 385.56 MiB free; 9.09 GiB reserved in total by PyTorch)
2021-03-19 12:09:30 | WARNING | fairseq.trainer | |===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 51           |        cudaMalloc retries: 66        |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |    6951 MB |    9130 MB |   16478 GB |   16471 GB |
|       from large pool |    6938 MB |    9118 MB |   16447 GB |   16441 GB |
|       from small pool |      12 MB |      16 MB |      30 GB |      30 GB |
|---------------------------------------------------------------------------|
| Active memory         |    6951 MB |    9130 MB |   16478 GB |   16471 GB |
|       from large pool |    6938 MB |    9118 MB |   16447 GB |   16441 GB |
|       from small pool |      12 MB |      16 MB |      30 GB |      30 GB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |    9308 MB |    9526 MB |  396082 MB |  386774 MB |
|       from large pool |    9294 MB |    9508 MB |  395864 MB |  386570 MB |
|       from small pool |      14 MB |      18 MB |     218 MB |     204 MB |
|---------------------------------------------------------------------------|
| Non-releasable memory |  569634 KB |     770 MB |    1982 GB |    1982 GB |
|       from large pool |  568358 KB |     766 MB |    1946 GB |    1946 GB |
|       from small pool |    1276 KB |      12 MB |      36 GB |      36 GB |
|---------------------------------------------------------------------------|
| Allocations           |     441    |     688    |    1162 K  |    1162 K  |
|       from large pool |     140    |     150    |     143 K  |     143 K  |
|       from small pool |     301    |     548    |    1019 K  |    1019 K  |
|---------------------------------------------------------------------------|
| Active allocs         |     441    |     688    |    1162 K  |    1162 K  |
|       from large pool |     140    |     150    |     143 K  |     143 K  |
|       from small pool |     301    |     548    |    1019 K  |    1019 K  |
|---------------------------------------------------------------------------|
| GPU reserved segments |      99    |     102    |    1279    |    1180    |
|       from large pool |      92    |      93    |    1170    |    1078    |
|       from small pool |       7    |       9    |     109    |     102    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |     103    |     120    |  547671    |  547568    |
|       from large pool |      78    |      80    |   60015    |   59937    |
|       from small pool |      25    |      44    |  487656    |  487631    |
|===========================================================================|
```

### environment
```
blas                      1.0                         mkl  
mkl                       2020.1                      217  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.1.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
torch                     1.7.1+cu101              pypi_0    pypi
torchaudio                0.7.2                    pypi_0    pypi
torchvision               0.8.2+cu101              pypi_0    pypi
```
I reduced the batch_size to 1, --empty-cache-freq to 1 ...still, OOM happens at the middle of training

**Comment by freewym** [comment]
Did it happen in the 1st epoch or later? Are you using the latest master?

**Comment by asifjalal** [comment]
Yes, it happened in the first epoch, but I am not using the latest master. I am using the version from January. Should I try using the latest one?

**Comment by freewym** [comment]
I just ran the swbd recipe in the latest master with PyTorch 1.7, CUDA Driver 440.33.01, CUDA toolkit 10.2 and 2 GTX1080 Ti GPUs (10.9 GB memory for each) and the 1st epoch went well. Try the latest one and see if your problem can be resolved.

**Comment by asifjalal** [comment]
Sorry for the delay :) This is working fine now. Thanks @freewym
